Vagrant.configure("2") do |config|
  # Provisioning private key for app
  config.vm.provision "file",
    source: "~/.ssh/app_key",
    destination: "/home/vagrant/.ssh/app_key"

    # Provisioning private key for db
  config.vm.provision "file",
    source: "~/.ssh/db_key",
    destination: "/home/vagrant/.ssh/db_key"

  # SSH private key paths
  config.ssh.private_key_path = [
    "~/.vagrant.d/insecure_private_key",
    "~/.ssh/app_key",  # Ensure this exists by running `ssh-keygen -t rsa -b 2048 -f ~/.ssh/app_key`
    "~/.ssh/db_key"    # Ensure this exists by running `ssh-keygen -t rsa -b 2048 -f ~/.ssh/db_key`
  ]

  config.vm.synced_folder "./h2_data", "/home/vagrant/h2_data"

  # Define the database VM
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "file",
        source: "~/.ssh/db_key.pub",
        destination: "~/.ssh/authorized_keys"
    db.vm.provision "shell", inline: <<-SHELL
      chmod 600 /home/vagrant/.ssh/db_key
    SHELL
    db.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "db_playbook.yml"
      ansible.inventory_path = "hosts.ini"
      ansible.extra_vars = { host: "db" }
      ansible.compatibility_mode = "2.0"
      ansible.raw_arguments = ["--ssh-extra-args='-o StrictHostKeyChecking=no'"]
    end
  end

  # Define the application VM
  config.vm.define "app" do |app|
    app.vm.box = "bento/ubuntu-22.04"
    app.vm.network "private_network", ip: "192.168.56.12"
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    app.vm.provision "file",
        source: "~/.ssh/app_key.pub",
        destination: "~/.ssh/authorized_keys"
    app.vm.provision "shell", inline: <<-SHELL
      chmod 600 /home/vagrant/.ssh/app_key
    SHELL
    app.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "app_playbook.yml"
      ansible.inventory_path = "hosts.ini"
      ansible.extra_vars = { host: "app" }
      ansible.compatibility_mode = "2.0"
      ansible.raw_arguments = ["--ssh-common-args='-o StrictHostKeyChecking=no'"]
    end
  end

  config.ssh.insert_key = false

end
